name: run-tests

# Only run this when the main branch changes
on:
  push:

# This job installs dependencies, builds the code and runs the hand rolled Python test framework
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # Install dependencies
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev build-essential

    - name: Build the code code
      run: |
          make all

    - name: Build the tests
      run: |
          make tests

    - name: Run tests
      run: |
          make runtests